"""
This file is auto-generated by phpy. Please do not modify it.
"""

<?php include __DIR__ . '/import.tpl'; ?>
<?= $importParentClass . PHP_EOL ?>


<?php include __DIR__ . '/annotation.tpl'; ?>
class <?=$this->_proxyClass?>(<?=implode(', ', $parents)?>):
  def __init__(self, _this):
    self.__this = _this
    _this.set('_super', super())
    _this.set('_self', self)
    _this.call('__init')

<?php foreach($methods as $m):?>
  def <?=$m['name']?>(self, <?=$m['argv']?>):
    return self.__this.call('<?=$m['name']?>', <?=$m['argv']?>)

<?php endforeach; ?>
