"""
This file is auto-generated by phpy. Please do not modify it.
"""

from enum import Enum
<?php include __DIR__ . '/import.tpl'; ?>


class <?=$class?>(Enum):
<?php foreach ($constants as $key => $value): ?>
    <?=$key?> = <?=PhpyTool\Tool::valueToRepr($value, true) . PHP_EOL ?>
<?php endforeach; ?>

