"""
This file is auto-generated by phpy. Please do not modify it.
"""

<?php include __DIR__ . '/import.tpl'; ?>
import phpy


<?php include __DIR__ . '/annotation.tpl'; ?>
def <?=$name?>(<?=$args?>)<?=$returnType?>:
    return phpy.call('<?=$name?>', <?=$argNames?>)

