"""
This file is auto-generated by phpy. Please do not modify it.
"""

<?php foreach($packages as $package): ?>
<?=$package.PHP_EOL?>
<?php endforeach; ?>
import phpy

<?php foreach($annotations as $annotation): ?>
@<?=$annotation.PHP_EOL?>
<?php endforeach; ?>
def <?=$name?>(<?=$args?>)<?=$returnType?>:
    return phpy.call('<?=$name?>', <?=$argNames?>)

